### ISSUE TITLE
Secure API Key Input

### ISSUE THREAD

**Issue by NoaTeomi** [J0nesycat/forecast#6]
1.API Key Input Security:

The new API key input functionality is convenient, making the setup easier. For enhanced security, consider checking for a valid key format before accepting it.
Suggested Improvement: Could we validate the API key format to ensure it meets OpenWeatherMap's requirements? It may reduce the chances of failed requests due to typos or formatting issues.
2. Logging API Key Access:

The current setup improves security by prompting users only once. For additional security, consider adding a one-time logging message when the key is entered.
Suggested Improvement: Can we add a log entry confirming that an API key was entered, without showing the key itself? This would be useful for tracking while ensuring the key remains hidden.

**Comment by J0nesycat** [comment]
Thank you for the detailed feedback!

The software has been updated to streamline API key management. Users no longer need to manually edit the apikey.py file. After successful authorization, the program securely prompts for the API key and stores it automatically.

Please check out these updates in release v1.0-api-key. Thanks again for your valuable insights!
